- name: Install git
  become: true
  apt:
    name: git 

- name: Git setup email
  git_config:
    name: user.email
    scope: global
    value: "rene.ruprecht.396@gmail.com"

- name: Git setup name
  git_config:
    name: user.name
    scope: global
    value: "ReneRuprecht"
