# zsh section
- name: Install zsh
  become: true
  apt:
    name: zsh

- name: Check zsh file
  stat:
    path: $HOME/.oh-my-zsh
  register: oh_my_stats

- name: Install oh-my-zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  when: oh_my_stats.stat.exists == false
  become_user: "{{user_name}}"

- name: Check powerlevel10k
  stat:
    path: $HOME/powerlevel10k
  register: powerlevel10k 

- name: install powerlevel10k
  shell: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k && echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >> ~/.zshrc
  when: powerlevel10k.stat.exists == false

